<?php

class TooLongDistanceException extends Exception {

	private $_distance;

	public function __construct($distance, $message = "", $code = 0, Exception $previous = null) {
		$this->$_distance = (double)$distance;
		parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
	}

	public function GetDistance() {
		return $this->_distance;
	}

}